# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZFPlayerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZFPlayerDemo

pod 'ZFPlayer'
pod 'ZFPlayer/ControlView'
pod 'ZFPlayer/AVPlayer'

end
